language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.9
  - 2.3.5
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
branches:
  only: master
script: bundle exec rake $TASK
env:
  - TASK=default
matrix:
  exclude:
    - rvm: 2.5.0
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.0.gemfile
  include:
    - rvm: 2.4.3
      gemfile: gemfiles/rails5.1.gemfile
      env: TASK=rubocop
